application: mycourse
version: 1
runtime: python27
api_version: 1
threadsafe: false
instance_class: F1

env_variables:
  GCB_PRODUCT_VERSION: '1.11.x'
  GCB_APPSTATS_ENABLED: false
  GCB_TEST_MODE: false
  GCB_PRELOADED_MODULES:
    modules.help_urls.help_urls
    modules.dashboard.dashboard
  GCB_THIRD_PARTY_MODULES: modules.student-dashboard.student-dashboard

includes:
- custom.yaml
- static.yaml

inbound_services:
- warmup

builtins:
- remote_api: on
- deferred: on

libraries:
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"
- name: pycrypto
  version: "2.6"
- name: webapp2
  version: "2.5.2"
- name: webob
  version: "1.2.3"
- name: lxml
  version: "2.3"

handlers:
- url: /modules/([^/]*)/_static/(.*)
  upload: modules/([^/]*)/_static/(.*)
  static_files: modules/\1/_static/\2
  expiration: 10m
  application_readable: true
- url: .*/favicon\.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon\.ico
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: always
- url: /cron/.*
  script: main.app
  login: admin
  secure: always
- url: /mapreduce/worker/.*
  script: main.app
  login: admin
  secure: always
- url: /.*
  script: main.app
  secure: always
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^internal/.*$
